name: Build and Test

on:
  push

# run multiple jobs in parallel
# dynamic matrix for different assignments

jobs:
  assignments:
    strategy:
      fail-fast: false
      matrix:
        assignment: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    #        os: [ubuntu-latest, macos-latest, windows-latest]

    #    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      # Checks-out the repo
      - name: Check Out Source Code
        uses: actions/checkout@v2

      # configure the build
      - name: cmake configure
        run: cmake -S . -B build

      # build the target
      - name: cmake build target
        run: cmake --build build --target assignment${{ matrix.assignment }}_tests

      # run the tests
      - name: run tests
        run: cd ./build/assignment${{ matrix.assignment }} ; ./assignment${{ matrix.assignment }}_tests

      # run the check format
      - name: run check proper format
        id: check-format
        run: cmake --build build --target check-clang-format
        continue-on-error: true

      # if there is a problem with the format, show the problem
      - name: print the format problem
        if: steps.check-format.outcome == 'failure'
        run: cmake --build build --target clang-format